# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20180322_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spent',
            field=models.FloatField(default=0),
        ),
    ]
