# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_auto_20180326_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cash_amount',
            new_name='number_of_stocks',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sec_fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='security',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='split_ratio',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default='0:0', verbose_name='transaction'),
            preserve_default=False,
        ),
    ]
