# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='transaction date')),
                ('security', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('date', models.DateField(verbose_name='transaction date')),
                ('security', models.CharField(blank=True, max_length=10)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sec_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('split_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Account')),
            ],
        ),
    ]
